apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fjsv8qh9a-go 
  janus-idp.io/tekton: fjsv8qh9a-go
  backstage.io/kubernetes-id: fjsv8qh9a-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fjsv8qh9a-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml